apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: open-webui-azure
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: hybrid-ai-platform
    environment: azure
spec:
  project: default
  
  source:
    repoURL: https://github.com/Z3ROX-lab/hybrid-ai-security-platform.git
    targetRevision: main
    path: kubernetes/azure/apps/open-webui
  
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-apps
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
