apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: langfuse
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://langfuse.github.io/langfuse-k8s
      chart: langfuse
      targetRevision: 1.5.20
      helm:
        releaseName: langfuse
        valueFiles:
          - $values/argocd/applications/langfuse/values.yaml
    - repoURL: https://github.com/Z3ROX-lab/hybrid-ai-security-platform.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
