apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openwebui
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://helm.openwebui.com
      chart: open-webui
      targetRevision: 12.3.0
      helm:
        releaseName: openwebui
        valueFiles:
          - $values/argocd/applications/openwebui/values.yaml
    - repoURL: https://github.com/Z3ROX-lab/hybrid-ai-security-platform.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
