apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app-azure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: https://github.com/Z3ROX-lab/hybrid-ai-security-platform.git
    targetRevision: main
    path: argocd/azure/applications
  
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
